"""Step 5: run every validation check and write data/processed/QA.md.

    python -m pipeline.qa        # exits non-zero if any check fails
"""

from __future__ import annotations

import sys

import duckdb
import pandas as pd

from .checks import run_all
from .common import DB_PATH, PROCESSED, sources_pinned


def known_gaps(con) -> str:
    """Differences we document rather than fail on."""
    gap = con.execute("""
        SELECT sum(pop_total), sum(pop_t16_all), sum(households) FROM district_counts
    """).fetchone()
    worst = con.execute("""
        SELECT district_name, round(100 * (1 - pop_t16_all / pop_total), 1) AS gap
        FROM district_counts ORDER BY gap DESC, district_name LIMIT 4
    """).fetchall()
    worst_txt = ", ".join(f"{n} {g}%" for n, g in worst)
    area = pd.read_csv(PROCESSED / "qa_district_area_check.csv")
    off = area[(area["ratio"] - 1).abs() > 0.10].sort_values(["ratio", "map_unit_id"])
    off_txt = ", ".join(f"{r.map_unit_id} {r.ratio:.2f}" for r in off.itertuples())
    return f"""
## Known differences (documented, not errors)

- **Detailed tables cover fewer people than Table 1.** Tables 12, 13 and 16 (age, literacy,
  disability) add up to {gap[1]:,.0f} people against Table 1's {gap[0]:,.0f}
  ({100 * (1 - gap[1] / gap[0]):.2f}% fewer). The gap is concentrated in {worst_txt}. Rates are
  computed within each table, so numerator and denominator always cover the same people.
- **Households.** Tables 20-25 sum to {gap[2] / 1e6:,.2f} million households; PBS's headline is
  38.32 million. Persons per household here (population / households) is
  {gap[0] / gap[2]:.2f}; PBS publishes 6.33 without stating its method in these tables.
- **Mapped areas.** {len(off)} of {len(area)} shapes differ from PBS's reported area by more
  than 10%: {off_txt}. Most are in Balochistan, where districts were redrawn below the
  tehsil level after the boundary data was made; see docs/methodology.md.
"""


def main() -> int:
    con = duckdb.connect(str(DB_PATH), read_only=True)
    checks = run_all(con)
    failed = [c for c in checks if not c.passed]

    lines = [
        "# Data quality report",
        "",
        f"Generated by `python -m pipeline.qa` from sources pinned on {sources_pinned():%d %B %Y}. "
        f"**{len(checks) - len(failed)} of {len(checks)} checks pass.**",
        "",
        "| | Group | Check | Result |",
        "|---|---|---|---|",
    ]
    for c in checks:
        mark = "✅" if c.passed else "❌"
        lines.append(f"| {mark} | {c.group} | {c.name} | {c.detail} |")
    lines.append(known_gaps(con))

    fixes = con.execute("SELECT id, \"table\", province, expected_rows, reason FROM applied_fixes").fetchall()
    lines += ["## Corrections applied to the source files", ""]
    for fid, table, province, rows, reason in fixes:
        lines.append(f"- **{fid}** ({table}, {province}, {rows} rows): {' '.join(reason.split())}")
    lines.append("- **Table 13a** is not used for the 5-16 population: its conversion left 143 cells blank, "
                 "every one a value above one million. Table 13b carries the same rows intact and agrees "
                 "with 13a on every count they share.")
    lines.append("")

    (PROCESSED / "QA.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"qa: {len(checks) - len(failed)}/{len(checks)} checks pass -> data/processed/QA.md")
    for c in failed:
        print(f"  FAILED [{c.group}] {c.name}: {c.detail}")
    con.close()
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
